apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    name: jenkins-pod
spec:
  containers:
  - name: jenkins-pod
    image: jenkinsci/blueocean
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      app: jenkins-deployment
  template:
    metadata:
      labels:
        app: jenkins-deployment
    spec:
      containers:
      - name: jenkins-deployment
        image: jenkinsci/blueocean
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080


---
  
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins-deployment
  ports:
  - port: 9898
    targetPort: 8080

