apiVersion: v1
kind: Pod
metadata:
  name: devopoc-pod
  labels:
    name: devopoc
spec:
  containers:
  - name: devopoc
    image: solwin/neodevops
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 3000
