apiVersion: v1
kind: Pod
metadata:
  name: devopoc-pod
  labels:
    name: devopoc
spec:
  containers:
  - name: devopoc
    image: solwin/devopoc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
