apiVersion: v1
kind: Service
metadata:
  name: devopoc-service
spec:
  type: LoadBalancer
  loadBalancerIP: 172.29.0.1
  ports:
  - port: 8383
    targetPort: 80
    nodePort: 32765
  selector:
    app: devopoc
  


